name: Configurable Build Matrix

on: push
jobs:
  preperation:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Generate json file
        run: |
          cd ./tests
          python json_creation.py
      - id: set-matrix
        uses: JoshuaTheMiller/conditional-build-matrix@0.0.1
        with:
          filter: '[?product]'
  tests:
    needs: preperation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.preperation.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2

      - name: Install ${{ matrix.product }} ${{ matrix.version }} on ${{ matrix.distro }}
        if: startsWith(matrix.distro,'ubuntu' || 'debian')
        run: | 
            docker run -v `pwd`:/scylla-web-install -w /scylla-web-install  --rm ${{ matrix.distro }} bash -c 'apt-get update && apt-get install -y curl wget && ./server --scylla-product ${{ matrix.product }} --scylla-version ${{ matrix.version }}'

      - name: Install ${{ matrix.product }} ${{ matrix.version }} on ${{ matrix.distro }}
        if: startsWith(matrix.distro,'centos' || 'rhel' || 'rocky' || 'oracle' || 'amazon')
        run: | 
            docker run -v `pwd`:/scylla-web-install -w /scylla-web-install  --rm ${{ matrix.distro }} bash -c 'dnf update && dnf install -y curl wget && ./server --scylla-product ${{ matrix.product }} --scylla-version ${{ matrix.version }}'

